<script setup>
    defineProps({
        current_user: Array,
        inventories: Array,
    })
</script>

<template>
    <div ref="content" class="pdf-content bg-white p-6">
        <!-- title  -->
        <div class="text-center mb-4">
            <h1 class="text-2xl font-bold text-uppercase">List of Inventory</h1>
            <!-- <p class="text-uppercase">({{ category }} Category)</p> -->
        </div>
        <!-- <p><strong>Exported by:</strong> {{ current_user.name }}</p> -->
        <p><strong>Campus:</strong> {{ current_user.campus }}</p>
        <!-- <p><strong>Exported at:</strong> Date</p> -->

        <!-- <div class="mt-4">
            <ul>
                <li v-for="(item, index) in enterprises" :key="index">
                    {{ index + 1 }}. {{ item.enterprise }} – {{ item.category }}
                </li>
            </ul>
        </div> -->

        <div class="mt-6">
            <table class="min-w-full divide-y divide-gray-200">
                <thead>
                    <tr class="bg-green-900 font-bold">
                        <th scope="col" class="px-6 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">#</th>
                        <th scope="col" class="px-6 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Product Name</th>
                        <th scope="col" class="px-6 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Quantity</th>
                        <th scope="col" class="px-6 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Price per unit</th>
                        <th scope="col" class="px-6 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Category</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200 text-uppercase">
                    <tr v-for="(item, index) in inventories" :key="index">
                        <td class="px-6 pb-3 whitespace-nowrap text-sm font-medium text-gray-900">{{ index + 1 }}.</td>
                        <td class="px-6 pb-3 whitespace-nowrap text-sm text-gray-500">{{ item.product_name }}</td>
                        <td class="px-6 pb-3 whitespace-nowrap text-sm text-gray-500">{{ item.quantity }}</td>
                        <td class="px-6 pb-3 whitespace-nowrap text-sm text-gray-500">{{ item.price }}</td>
                        <td class="px-6 pb-3 whitespace-nowrap text-sm text-gray-500">{{ item.category }}</td>
                    </tr>
                    <tr>
                        <td class="px-6 pb-3 whitespace-nowrap text-sm font-medium text-gray-900" colspan="5" style="text-align: center;">
                            ----- Nothing Follows -----
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- generated or printed by  -->
        <!-- <div class="mt-16 flex justify-end mr-16">
            <div class="text-center">
                <p class="text-uppercase font-bold">{{ current_user.name }}</p>
                <p>Generated By</p>
            </div>
        </div> -->
    </div>
</template>

<style scoped>
    .pdf-content {
        width: 800px;
        background-color: white;
    }
</style>
