<script setup>
    defineProps({
        current_user: Array,
        headers: Array,
        title: String,
        subtext: String
    })
</script>

<template>
    <div ref="content" class="pdf-content bg-white p-6">
        <!-- title  -->
        <div class="text-center mb-4">
            <h1 class="text-2xl font-bold text-uppercase">{{ title }}</h1>
            <p v-if="subtext" class="text-uppercase">{{ subtext }}</p>
        </div>
        <!-- <p><strong>Exported by:</strong> {{ current_user.name }}</p> -->
        <p v-if="current_user.role == 'User'"><strong>Campus:</strong> {{ current_user.campus }}</p>
        <p v-else><strong>Campus:</strong> All</p>
        <!-- <p><strong>Exported at:</strong> Date</p> -->

        <!-- <div class="mt-4">
            <ul>
                <li v-for="(item, index) in enterprises" :key="index">
                    {{ index + 1 }}. {{ item.enterprise }} – {{ item.category }}
                </li>
            </ul>
        </div> -->

        <div class="mt-6">
            <table class="min-w-full divide-y divide-gray-200">
                <thead>
                    <tr class="bg-green-900 font-bold">
                        <th v-for="header in headers" :key="header" scope="col" class="px-6 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">{{ header }}</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200 text-uppercase">
                    <slot />
                    <tr>
                        <td class="px-6 pb-3 whitespace-nowrap text-sm font-medium text-gray-900" :colspan="headers.length" style="text-align: center;">
                            ----- Nothing Follows -----
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- generated or printed by  -->
        <!-- <div class="mt-16 flex justify-end mr-16">
            <div class="text-center">
                <p class="text-uppercase font-bold">{{ current_user.name }}</p>
                <p>Generated By</p>
            </div>
        </div> -->
    </div>
</template>

<style scoped>
    .pdf-content {
        width: 100%;
        background-color: white;
    }
</style>