<script setup>
    defineProps({
        current_user: Array,
        user_accounts: Array,
        total_users: Array
    })
</script>

<template>
    <div ref="content" class="pdf-content bg-white p-6">
        <!-- title  -->
        <div class="text-center mb-4">
            <h1 class="text-2xl font-bold text-uppercase">List of User Accounts</h1>
            <!-- <p class="text-uppercase">({{ category }} Category)</p> -->
        </div>
        <!-- <p><strong>Exported by:</strong> {{ current_user.name }}</p> -->
        <!-- <p><strong>Campus:</strong> {{ current_user.campus }}</p> -->
        <!-- <p><strong>Exported at:</strong> Date</p> -->

        <!-- <div class="mt-4">
            <ul>
                <li v-for="(item, index) in enterprises" :key="index">
                    {{ index + 1 }}. {{ item.enterprise }} – {{ item.category }}
                </li>
            </ul>
        </div> -->

        <div class="mt-6">
            <table class="min-w-full divide-y divide-gray-200">
                <thead>
                    <tr class="bg-green-900 font-bold">
                        <th scope="col" class="px-4 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">#</th>
                        <th scope="col" class="px-4 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Name</th>
                        <th scope="col" class="px-4 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Sex</th>
                        <th scope="col" class="px-4 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Campus</th>
                        <th scope="col" class="px-4 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Designation</th>
                        <th scope="col" class="px-4 pb-3 text-left text-xs font-medium text-white uppercase tracking-wider">Email</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200 ">
                    <tr v-for="(item, index) in user_accounts" :key="index">
                        <td class="px-4 pb-3 whitespace-nowrap text-xs font-medium text-gray-900">{{ index + 1 }}.</td>
                        <td class="px-4 pb-3 whitespace-nowrap text-xs text-gray-500">{{ item.full_name }}</td>
                        <td class="px-4 pb-3 whitespace-nowrap text-xs text-gray-500">{{ item.sex[0] }}</td>
                        <td class="px-4 pb-3 whitespace-nowrap text-xs text-gray-500">{{ item.campus }}</td>
                        <td class="px-4 pb-3 whitespace-nowrap text-xs text-gray-500">{{ item.designation }}</td>
                        <td class="px-4 pb-3 whitespace-nowrap text-xs text-gray-500">{{ item.email }}</td>
                    </tr>
                    <tr>
                        <td class="px-4 pb-3 whitespace-nowrap text-xs font-medium text-gray-900" colspan="6" style="text-align: center;">
                            ----- Nothing Follows -----
                        </td>
                    </tr>
                    <tr>
                        <td class="px-4 pb-3 whitespace-nowrap text-xs font-medium text-gray-900" colspan="6" style="text-align: left;">
                            Male: {{ total_users.total_male }}  Female: {{ total_users.total_female }}  Total: {{ total_users.total_overall }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- generated or printed by  -->
        <!-- <div class="mt-16 flex justify-end mr-16">
            <div class="text-center">
                <p class="text-uppercase font-bold">{{ current_user.name }}</p>
                <p>Generated By</p>
            </div>
        </div> -->
    </div>
</template>

<style scoped>
    .pdf-content {
        width: 800px;
        background-color: white;
    }
</style>